### ISSUE TITLE
ALPN support

### ISSUE THREAD

**Issue by quininer** [tower-rs/tower-hyper#9]
Currently the `tower-hyper` client is unable to get ALPN negotiation results from `Connector`.

We should try to support this. For example, add a trait to `<C as MakeConnection<A>>::Response` to get negotiation result of ALPN.

```rust
use http::version::Version;

trait Alpn {
    fn get_version(&self) -> Version;
}


impl<A, B, C> Service<A> for Connect<A, B, C>
where
    C: MakeConnection<A> + 'static,
    B: Payload + 'static,
    C::Response: Alpn + Send + 'static,
{
    // ...
}

// ...

            self.builder.http2_only(io.get_version() == Version::HTTP_2);
            let handshake = self.builder.handshake(io);
            self.state = State::Handshake(handshake);

// ...
```

I don't think this is a elegant solution, maybe you have a better idea. :)

**Comment by LucioFranco** [comment]
Thank you for opening this issue. I think it may be a good idea top add a `(AsyncRead + AsyncWrite, Self::Extra)` to the `MakeConnection::Response` type for things like this.  The issue is `TcpStream` doesnt support the ability to add a trait fn like this and `MakeConnection` requires taht response is `AsyncRead + AsyncWrite`. What do you think about that addition to `MakeConnection`?

**Comment by LucioFranco** [comment]
so what im thinking is that for example here MakeConnection returns the hyper Connected struct.

**Comment by quininer** [comment]
I like this idea!

**Comment by quininer** [comment]
I think that we can't just return `Connected` because it doesn't provide access methods. :(

**Comment by LucioFranco** [comment]
I was thinking we could modify it like so

```rust
pub trait MakeConnection<Request> {
	type Extra;
    /// The transport provided by this service
    type Transport: AsyncRead + AsyncWrite;

    /// Errors produced by the connecting service
    type Error;

    /// The future that eventually produces the transport
    type Future: Future<Item = (Self::Transport, Self::Extra), Error = Self::Error>;

    /// Connect and return a transport asynchronously
    fn make_connection(&mut self, target: Request) -> Self::Future;
}
```

Then for tower-hyper we can provide another trait to provide those verison checking functions and use that as the bound for `Extra`.

**Comment by quininer** [comment]
I just [tried it](https://github.com/quininer/tower/commit/263feebb999ddbc68efdbb09775d3591e12e556c).

~~I think we need to return our own `Connected` instead of hyper, because~~ [hyper `Connected`](https://docs.rs/hyper/0.12.25/hyper/client/connect/struct.Connected.html) is a write-only type, and we can't get the information we want.

Maybe hyper is willing to provide some access methods.

**Comment by LucioFranco** [comment]
Beyond, writing the new trait, did you actually try it with an impl of MakeConnection? Not sure I totally follow why we need a concrete type?

**Comment by quininer** [comment]
I am not against traits, I am just replying to https://github.com/tower-rs/tower-hyper/issues/9#issuecomment-468038350.

**Comment by LucioFranco** [comment]
Ah i see, so what im kinda thinking is that we can make a `HttpMakeConnection` kinda trait that has a bound on `typ Extra: HttpExtra` where 

```rust
pub trait HttpExtra {
	fn version() -> HttpVersion;
}
```

**Comment by LucioFranco** [comment]
#24 and check out https://github.com/hyperium/http-connection
